# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: proto/settings/v1/color.proto, proto/settings/v1/constraint_type.proto, proto/settings/v1/list.proto, proto/settings/v1/list_options.proto, proto/settings/v1/range.proto, proto/settings/v1/settings.proto, proto/settings/v1/string.proto, proto/settings/v1/value.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import (
    List,
    Optional,
)

import betterproto


class ColorFormatProto(betterproto.Enum):
    UNSPECIFIED = 0
    HEX = 1
    RGB = 2
    HSV = 3


class ConstraintTypeProto(betterproto.Enum):
    UNSPECIFIED = 0
    RANGE = 1
    LIST = 2
    STRING = 3
    COLOR = 4
    BOOLEAN = 5
    LIST_OPTIONS = 8


@dataclass(eq=False, repr=False)
class ColorConstraintProto(betterproto.Message):
    format: "ColorFormatProto" = betterproto.enum_field(1)
    range_mode: bool = betterproto.bool_field(2)


@dataclass(eq=False, repr=False)
class ListConstraintProto(betterproto.Message):
    min_length: int = betterproto.int32_field(2)
    max_length: int = betterproto.int32_field(3)


@dataclass(eq=False, repr=False)
class SettingValueProto(betterproto.Message):
    int_value: int = betterproto.int32_field(1, group="scalar_value")
    string_value: str = betterproto.string_field(2, group="scalar_value")
    bool_value: bool = betterproto.bool_field(3, group="scalar_value")
    float_value: float = betterproto.float_field(4, group="scalar_value")
    bytes_value: bytes = betterproto.bytes_field(5, group="scalar_value")
    int_array_value: List[int] = betterproto.int32_field(6)
    string_array_value: List[str] = betterproto.string_field(7)
    bool_array_value: List[bool] = betterproto.bool_field(8)
    float_array_value: List[float] = betterproto.float_field(9)
    bytes_array_value: List[bytes] = betterproto.bytes_field(10)


@dataclass(eq=False, repr=False)
class ListOptionsConstraintProto(betterproto.Message):
    options: List["SettingValueProto"] = betterproto.message_field(1)
    allow_multiple: bool = betterproto.bool_field(2)
    """
    If true, the user can select multiple options from the list.
    If false, the user can only select one option.
    """


@dataclass(eq=False, repr=False)
class RangeConstraintProto(betterproto.Message):
    min: Optional[float] = betterproto.message_field(1, wraps=betterproto.TYPE_FLOAT)
    max: Optional[float] = betterproto.message_field(2, wraps=betterproto.TYPE_FLOAT)
    step: Optional[float] = betterproto.message_field(3, wraps=betterproto.TYPE_FLOAT)


@dataclass(eq=False, repr=False)
class StringConstraintProto(betterproto.Message):
    min_length: Optional[int] = betterproto.message_field(
        1, wraps=betterproto.TYPE_INT32
    )
    max_length: Optional[int] = betterproto.message_field(
        2, wraps=betterproto.TYPE_INT32
    )
    pattern: Optional[str] = betterproto.message_field(3, wraps=betterproto.TYPE_STRING)


@dataclass(eq=False, repr=False)
class ConstraintConfigProto(betterproto.Message):
    range: "RangeConstraintProto" = betterproto.message_field(1, group="config")
    list_options: "ListOptionsConstraintProto" = betterproto.message_field(
        2, group="config"
    )
    color: "ColorConstraintProto" = betterproto.message_field(3, group="config")
    string: "StringConstraintProto" = betterproto.message_field(4, group="config")
    list: "ListConstraintProto" = betterproto.message_field(5, group="config")


@dataclass(eq=False, repr=False)
class ConstraintProto(betterproto.Message):
    type: "ConstraintTypeProto" = betterproto.enum_field(4)
    constraint: "ConstraintConfigProto" = betterproto.message_field(5)


@dataclass(eq=False, repr=False)
class SettingMetaProto(betterproto.Message):
    name: str = betterproto.string_field(1)
    category: str = betterproto.string_field(2)
    description: str = betterproto.string_field(3)
    default: "SettingValueProto" = betterproto.message_field(4)
    constraint: "ConstraintProto" = betterproto.message_field(5)
