version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/synapselib"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/ui/synapseui"
    schedule:
      interval: "weekly"
