network:
  server: true
  name: Vision-Py
  server_ip: 127.0.0.1

global:
  camera_matrix:
    0:
      - [672.38531251,   0.      ,   348.05954802]
      - [  0.   ,      649.66430117, 211.96006488]
      - [  0. ,          0.      ,     1.        ]
  camera_transform:
    0:
      - [0, 0, 0] # translation
      - [0, 0, 0] # rotation

camera_configs:
  0:
    default_pipeline: 0

pipelines:
  0: 
    type: ApriltagPipeline
    settings:
      target_tag: 7
      brightness: 100
      exposure: 20
      width: 600
      height: 600
      fieldpose: true
      saturation: 10
  1:
    type: ApriltagPipeline
    settings:
      target_tag: 12
      brightness: 100
      exposure: 20
      width: 1920
      height: 1080
