network:
  server: false
  name: Vision-Py
  team_number: 9738

global:
  camera_configs:
    0:
      default_pipeline: 0
      name: Monochrome
      path: /dev/video0
      matrix:
        - [850.07889429, 0.      ,     661.79650612]
        - [  0.   ,      896.26681121, 347.26132123]
        - [  0. ,        0.      ,     1.        ]
      transform:
        - [0.24496 ,-0.23167, 0.28991] # translation
        - [-1.86, -4, -24.95] # rotation
      distCoeffs:  
      - [ -0.06375875, 0.2054797,  -0.00232733,  -0.02853246,  -0.39985226]

pipelines:
  0: 
    type: ApriltagPipeline
    settings:
      target_tag: 7
      brightness: 100
      exposure: 20
      width: 600
      height: 600
      fieldpose: true
      saturation: 10
      orientation: 180
      tag_size: 0.1651
  1:
    type: ColorPipeline
    settings:
      brightness: 100
      exposure: 20
      width: 1920
      height: 1080
      minSize: 0.001
      lower: [1, 2, 3]
      upper: [4, 5, 6]
      color_space: RGB
