network:
  name: Vision-Py
  team_number: 9738

global:
  camera_configs:
    0:
      default_pipeline: 0
      name: Monochrome
      path: /dev/video0
      matrix:
        - [875.06274105, 0.0      ,     635.85143025]
        - [  0.   ,      880.2467956, 407.8149521]
        - [  0. ,        0.      ,     1.        ]
      distCoeffs:  
      - [ -0.02259194, 0.04796089,  0.01757909,  0.00100934,  -0.11873972]
      measured_res: [1280, 720]
      stream_res: [320, 180]
      transform:
        - [-0.24637, 0.23285, 0.28899] # translation
        - [1.86, 4, -24.95] # rotation

pipelines:
  0: 
    type: ApriltagPipeline
    settings:
      target_tag: 7
      brightness: 100
      exposure: 20
      width: 1280
      height: 720
      stick_to_ground: true
      fieldpose: true
      saturation: 10
      black_level_offset: 0.0
      orientation: 180
      tag_size: 0.1651
  1:
    type: ColorPipeline
    settings:
      brightness: 100
      exposure: 20
      width: 1920
      height: 1080
      minSize: 0.001
      lower: [1, 2, 3]
      upper: [4, 5, 6]
      color_space: RGB
