# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: proto/v1/camera.proto, proto/v1/device.proto, proto/v1/message.proto, proto/v1/pipeline.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import List

import betterproto

from ..settings import v1 as _settings_v1__


class MessageTypeProto(betterproto.Enum):
    UNSPECIFIED = 0
    SEND_DEVICE_INFO = 1
    SEND_METRICS = 2
    ADD_PIPELINE = 3


@dataclass(eq=False, repr=False)
class CameraProto(betterproto.Message):
    name: str = betterproto.string_field(1)
    stream_path: str = betterproto.string_field(2)
    physical_connection: str = betterproto.string_field(3)
    index: int = betterproto.int32_field(4)


@dataclass(eq=False, repr=False)
class LatencyStatusProto(betterproto.Message):
    latency_capture: int = betterproto.int64_field(1)
    latency_process: int = betterproto.int64_field(2)


@dataclass(eq=False, repr=False)
class DeviceInfoProto(betterproto.Message):
    hostname: str = betterproto.string_field(1)
    ip: str = betterproto.string_field(2)
    platform: str = betterproto.string_field(3)
    network_interfaces: List[str] = betterproto.string_field(4)


@dataclass(eq=False, repr=False)
class HardwareMetricsProto(betterproto.Message):
    cpu_temp: float = betterproto.float_field(1)
    cpu_usage: float = betterproto.float_field(2)
    disk_usage: float = betterproto.float_field(3)
    ram_usage: float = betterproto.float_field(4)
    memory: float = betterproto.float_field(5)
    uptime: float = betterproto.float_field(6)
    last_fetched: str = betterproto.string_field(7)


@dataclass(eq=False, repr=False)
class PipelineTypeProto(betterproto.Message):
    type: str = betterproto.string_field(1)
    settings: List["_settings_v1__.SettingProto"] = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class PipelineProto(betterproto.Message):
    name: str = betterproto.string_field(1)
    index: int = betterproto.uint32_field(2)
    type: "PipelineTypeProto" = betterproto.message_field(3)


@dataclass(eq=False, repr=False)
class MessageProto(betterproto.Message):
    type: "MessageTypeProto" = betterproto.enum_field(1)
    device_info: "DeviceInfoProto" = betterproto.message_field(2, group="payload")
    hardware_metrics: "HardwareMetricsProto" = betterproto.message_field(
        3, group="payload"
    )
    camera_info: "CameraProto" = betterproto.message_field(4, group="payload")
    pipeline_info: "PipelineProto" = betterproto.message_field(5, group="payload")
