/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import static org.junit.jupiter.api.Assertions.*;

/** A simple functional test for the 'org.example.greeting' plugin. */
class Synapse_cli_pluginPluginFunctionalTest {}
