/*
 * This source file was generated by the Gradle 'init' task
 */
package synapse.plugin;

import org.gradle.api.Plugin;
import org.gradle.api.Project;

/**
 * A simple 'hello world' plugin.
 */
public class Synapse_cli_pluginPlugin implements Plugin<Project> {
    @Override
    public void apply(Project project) {
        StartupSettingsExtension ext = project.getExtensions().create("synapse", StartupSettingsExtension.class);
        var deploy = project.getTasks().register("synapseDeploy", DeployTask.class, task -> {
            task.doFirst(t -> {
                if (ext.getProjectName() == null) {
                    throw new IllegalArgumentException("synapse.projectName must be set");
                }
                assert ext.getDeviceName() != null;

                task.commandLine("python", "-m" , "synapse_installer", "deploy");
                task.args(ext.getDeviceName());
            });
        });
    }
}
