name: Synapse Networking

on:
  push:
    branches:
      - main
    paths:
      - '**/*.proto'
      - 'synapse_net/proto/buf.yaml'
      - 'synapse_net/proto/buf.gen.yaml'
  pull_request:
    paths:
      - '**/*.proto'
      - 'synapse_net/proto/buf.yaml'
      - 'synapse_net/proto/buf.gen.yaml'

jobs:
  protobuf:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.7'

      - name: Install Buf CLI
        uses: bufbuild/buf-setup-action@v1.50.0

      - name: Check Buf version
        run: buf --version

      - name: Check protobuf format
        run: buf format --diff
        working-directory: synapse_net/proto

      - name: Lint protobuf files
        run: buf lint
        working-directory: synapse_net/proto

      - name: Build protobuf files
        run: buf build
        working-directory: synapse_net/proto
