name: Synapse ARM CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_arm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies for QEMU and image mounting
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static binfmt-support qemu-utils

      - name: Download ARM disk image
        run: |
          wget -O image.img.xz https://github.com/Joshua-Riek/ubuntu-rockchip/releases/download/v2.4.0/ubuntu-24.04-preinstalled-server-arm64-orangepi-5.img.xz
          unxz image.img.xz

      - name: Setup NBD and mount root partition
        run: |
          sudo modprobe nbd max_part=8
          sudo qemu-nbd --connect=/dev/nbd0 image.img
          sleep 3
          sudo mkdir -p /mnt/arm-root
          sudo mount /dev/nbd0p2 /mnt/arm-root  # adjust partition if necessary

      - name: Copy repo into image
        run: |
          sudo rsync -a --delete ./ /mnt/arm-root/root/Synapse/

      - name: Copy qemu static binary for ARM emulation
        run: |
          sudo cp /usr/bin/qemu-aarch64-static /mnt/arm-root/usr/bin/

      - name: Run build inside chroot
        run: |
          sudo chroot /mnt/arm-root /bin/bash -c "
            cd /root/Synapse &&
            python3 -m pip install . &&
            python3 -m pip install '.[dev]' &&
            python3 -m build
          "

      - name: Cleanup mounts
        run: |
          sudo umount /mnt/arm-root
          sudo qemu-nbd --disconnect /dev/nbd0

      - name: Compress modified image
        run: |
          xz -T0 image.img

      - name: Upload built image artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-arm-image
          path: image.img.xz

  test_arm:
    needs: build_arm
    runs-on: ubuntu-latest

    steps:
      - name: Download built image artifact
        uses: actions/download-artifact@v4
        with:
          name: built-arm-image

      - name: Decompress image
        run: unxz image.img.xz

      - name: Install dependencies for QEMU and image mounting
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu qemu-user-static binfmt-support qemu-utils

      - name: Setup NBD and mount root partition
        run: |
          sudo modprobe nbd max_part=8
          sudo qemu-nbd --connect=/dev/nbd0 image.img
          sleep 3
          sudo mkdir -p /mnt/arm-root
          sudo mount /dev/nbd0p2 /mnt/arm-root  # adjust partition if necessary

      - name: Copy qemu static binary for ARM emulation
        run: |
          sudo cp /usr/bin/qemu-aarch64-static /mnt/arm-root/usr/bin/

      - name: Run tests inside chroot
        run: |
          sudo chroot /mnt/arm-root /bin/bash -c "
            cd /root/Synapse &&
            pytest
          "

      - name: Cleanup mounts
        run: |
          sudo umount /mnt/arm-root
          sudo qemu-nbd --disconnect /dev/nbd0
