name: Synapse Bridge

on:
  push:
    branches: [main]
    paths:
      - 'synapse_bridge/**'
  pull_request:
    paths:
      - 'synapse_bridge/**'
        
permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Project
        run: |
          cd synapse_bridge
          ./gradlew build 

  spotless-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Spotless Check
        run: |
          cd synapse_bridge
          ./gradlew spotlessCheck
