name: Synapse Bridge

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin' 
        java-version: '17'

    - name: Download Dependencies
      run: |
        mkdir -p bridge/libs
        curl -L -o bridge/libs/ntcore-java-2025.2.1.jar https://frcmaven.wpi.edu/release/edu/wpi/first/ntcore/ntcore-java/2025.2.1/ntcore-java-2025.2.1.jar
        curl -L -o bridge/libs/wpimath-java-2025.2.1.jar https://frcmaven.wpi.edu/release/edu/wpi/first/wpimath/wpimath-java/2025.2.1/wpimath-java-2025.2.1.jar
        curl -L -o bridge/libs/jackson-core-2.13.0.jar https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.13.0/jackson-core-2.13.0.jar
        curl -L -o bridge/libs/jackson-databind-2.13.0.jar https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.13.0/jackson-databind-2.13.0.jar
        curl -L -o bridge/libs/jackson-annotations-2.13.0.jar https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.13.0/jackson-annotations-2.13.0.jar

    - name: Build Check
      run: |
        cd bridge
        mkdir -p out
        javac -d out -cp "libs/*" *.java
