name: Synapse Lib

on:
  push:
    branches: [main]
    paths:
      - "synapse_lib/**"
  pull_request:
    paths:
      - "synapse_lib/**"

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Build Project
        run: |
          cd synapse_lib
          ./gradlew build

  spotless-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Run Spotless Check
        run: |
          cd synapse_lib
          ./gradlew spotlessCheck
